name: Build x86 tarball

on:
  push:
  workflow_dispatch:

jobs:
  build-tarball:
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build a tarball
      run: ./dist.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: tarball
        path: dist/mold-*.tar.gz
