name: Build all tarballs

on:
  schedule:
    - cron: '0 0 * * *'
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build-tarballs:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        target: [ x86_64, aarch64, arm, riscv64, ppc64le, s390x ]

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Build a tarball
      run: ./dist.sh ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: dist/mold-*.tar.gz
