name: Build all tarballs

on:
  schedule:
    - cron: '0 0 * * *'
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  build-tarballs:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [ x86_64, aarch64, arm, riscv64, ppc64le, s390x ]

    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Podman and QEMU
      run: |
        sudo apt-get update
        sudo apt-get install -y podman qemu-user-static

    - name: Login to GitHub Container Registry
      run: podman login ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}

    - name: Build a tarball
      run: ./dist.sh ${{ matrix.target }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.target }}
        path: mold-*.tar.gz
